# Generated by Django 5.2.2 on 2025-06-28 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_trabajador_tipo_trabajador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='tipo_trabajador',
        ),
    ]
