# Generated by Django 5.2.2 on 2025-06-28 19:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del producto",
                        max_length=200,
                        verbose_name="Nombre del Producto",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada del producto",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio del producto en USD (sin IVA)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Precio",
                    ),
                ),
                (
                    "iva",
                    models.IntegerField(
                        choices=[(0, "0% IVA"), (15, "15% IVA")],
                        default=15,
                        help_text="Porcentaje de IVA aplicable (0% o 15%)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(15),
                        ],
                        verbose_name="IVA",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen del producto (opcional)",
                        null=True,
                        upload_to="productos/",
                        verbose_name="Imagen",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="productos_p_nombre_456643_idx"
                    ),
                    models.Index(
                        fields=["precio"], name="productos_p_precio_d043df_idx"
                    ),
                ],
            },
        ),
    ]
