# Generated by Django 5.2.2 on 2025-06-29 01:05

import os
import shutil
from django.db import migrations
from django.conf import settings


def add_product_images(apps, schema_editor):
    """Add images to existing productos."""
    Producto = apps.get_model('productos', 'Producto')
    
    # Create media directory if it doesn't exist
    media_productos_dir = os.path.join(settings.MEDIA_ROOT, 'productos')
    os.makedirs(media_productos_dir, exist_ok=True)
    
    # Source directory for fixture images
    fixtures_dir = os.path.join(settings.BASE_DIR, 'static', 'fixtures', 'productos')
    
    # Mapping of product names to image files
    product_images = {
        'Llantas Deportivas Aleación': 'llantas_deportivas.jpg',
        'Sistema Audio Premium': 'sistema_audio.png',
        'Kit Iluminación LED Interior': 'led_interior.jpg'
    }
    
    for product_name, imagen_filename in product_images.items():
        try:
            producto = Producto.objects.get(nombre=product_name)
            
            # Copy image from fixtures to media directory
            source_path = os.path.join(fixtures_dir, imagen_filename)
            dest_path = os.path.join(media_productos_dir, imagen_filename)
            
            if os.path.exists(source_path):
                shutil.copy2(source_path, dest_path)
                producto.imagen = f'productos/{imagen_filename}'
                producto.save()
        except Producto.DoesNotExist:
            pass  # Skip if product doesn't exist


def remove_product_images(apps, schema_editor):
    """Remove images from productos."""
    Producto = apps.get_model('productos', 'Producto')
    
    for producto in Producto.objects.all():
        producto.imagen = None
        producto.save()


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20250628_1956'),
    ]

    operations = [
        migrations.RunPython(add_product_images, remove_product_images),
    ]
