# Generated by Django 5.2.2 on 2025-06-29 00:57

from django.db import migrations


def populate_proveedores(apps, schema_editor):
    """Populate proveedores with mock data."""
    Proveedor = apps.get_model('proveedores', 'Proveedor')
    
    # Skip if proveedores already exist
    if Proveedor.objects.exists():
        return
    
    # Mock supplier data from different South American countries
    proveedores_data = [
        {
            'nombre': 'AutoPartes Colombia S.A.S.',
            'descripcion': 'Empresa líder en la distribución de autopartes y accesorios automotrices en Colombia.',
            'telefono': '+57 1 4567890',
            'pais': 'Colombia',
            'correo': 'ventas@autopartescolombia.com',
            'direccion': 'Carrera 15 #85-32, Zona Industrial, Bogotá D.C.'
        },
        {
            'nombre': 'TecnoAuto Argentina',
            'descripcion': 'Proveedor especializado en tecnología automotriz y sistemas de iluminación LED.',
            'telefono': '+54 11 9876543',
            'pais': 'Argentina',
            'correo': 'contacto@tecnoautoarg.com.ar',
            'direccion': 'Av. Córdoba 1234, Villa Crespo, Buenos Aires (C1414)'
        },
        {
            'nombre': 'AutoSupply Brasil Ltda.',
            'descripcion': 'Importadora y distribuidora de accesorios automotrices premium.',
            'telefono': '+55 11 3456789',
            'pais': 'Brasil',
            'correo': 'comercial@autosupplybr.com.br',
            'direccion': 'Rua das Indústrias, 567 - Vila Leopoldina, São Paulo - SP'
        },
        {
            'nombre': 'Motortech Chile Spa',
            'descripcion': 'Empresa especializada en tecnología automotriz avanzada y componentes de alta performance.',
            'telefono': '+56 2 9876543',
            'pais': 'Chile',
            'correo': 'ventas@motortechchile.cl',
            'direccion': 'Av. Providencia 2250, Providencia, Santiago'
        },
        {
            'nombre': 'Auto Repuestos Peru SAC',
            'descripcion': 'Líder en distribución de repuestos y accesorios automotrices en Perú.',
            'telefono': '+51 1 7654321',
            'pais': 'Perú',
            'correo': 'info@autorepuestosperu.pe',
            'direccion': 'Jr. Puno 1456, La Victoria, Lima 13'
        },
        {
            'nombre': 'VehiParts Ecuador Cía. Ltda.',
            'descripcion': 'Importadora ecuatoriana de autopartes originales y aftermarket.',
            'telefono': '+593 2 3456789',
            'pais': 'Ecuador',
            'correo': 'comercial@vehipartsec.com',
            'direccion': 'Av. 6 de Diciembre N24-253, Quito - Pichincha'
        }
    ]
    
    for proveedor_data in proveedores_data:
        Proveedor.objects.create(**proveedor_data)


def reverse_populate_proveedores(apps, schema_editor):
    """Remove populated proveedores."""
    Proveedor = apps.get_model('proveedores', 'Proveedor')
    Proveedor.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_proveedores, reverse_populate_proveedores),
    ]
